/** User */
export const SET_USERNAME = 'SET_USERNAME'

/** Device */
export const SET_CURR_DEVICE = 'SET_CURR_DEVICE'
export const SET_DEVICE_LIST = 'SET_DEVICE_LIST'
export const SET_PRESET_ROW = 'SET_PRESET_ROW'
export const SET_PRESET_COL = 'SET_PRESET_COL'
export const SET_PRESET_MIN_COL = 'SET_PRESET_MIN_COL'
export const SET_PRESET_MIN_ROW = 'SET_PRESET_MIN_ROW'
export const SET_PRESET_GROUP_LIST = 'SET_PRESET_GROUP_LIST'
export const SET_GROUP_LIST = 'SET_GROUP_LIST'
export const SET_DATA = 'SET_DATA'
export const SET_OLD_DATA = 'SET_OLD_DATA'
export const SET_SHOWX = 'SET_SHOWX'
export const SET_SHOWY = 'SET_SHOWY'
export const SET_SELECT_RES = 'SET_SELECT_RES'
export const SET_SELECT_RUSH = 'SET_SELECT_RUSH'
export const SET_SELECT_TYPE = 'SET_SELECT_TYPE'
export const SET_RESOLUTION_LIST = 'SET_RESOLUTION_LIST'
export const SET_IS_CHANGE_GROUP_LIST = 'SET_IS_CHANGE_GROUP_LIST'
export const SET_CURR_SELECT_GROUPID = 'SET_CURR_SELECT_GROUPID'
export const SET_EVERY_BY_VAL = 'SET_EVERY_BY_VAL'
export const SET_SPLICE_SETTING = 'SET_SPLICE_SETTING'
export const SET_CONFIRM_SETTING_COMMAND_LIST = 'SET_CONFIRM_SETTING_COMMAND_LIST'
export const OPERATION_DEVICE = 'OPERATION_DEVICE'
export const SET_CART_LIST = 'SET_CART_LIST'
export const SET_INPUT_CART_LIST = 'SET_INPUT_CART_LIST'
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'

/** PopWindow */
export const SET_CURR_WINDOW = 'SET_CURR_WINDOW'
export const SET_CURR_DEVICE_PRO = 'SET_CURR_DEVICE_PRO'

/* Connect */
export const SET_TYPE_OBJ = 'SET_TYPE_OBJ'
export const SET_LOG_NAME = 'SET_LOG_NAME'
